----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:11:08
--
--      Input file      : 
--      Component name  : and_16
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY and_16 IS
   PORT (
      y  : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      a  : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
      b  : IN STD_LOGIC_VECTOR(15 DOWNTO 0)
   );
END and_16;

ARCHITECTURE trans OF and_16 IS
   COMPONENT and_gate IS
      PORT (
         out_xhdl1 : OUT STD_LOGIC;
         a  : IN STD_LOGIC;
         b  : IN STD_LOGIC
      );
   END COMPONENT;
   
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL y_xhdl0 : STD_LOGIC_VECTOR(15 DOWNTO 0);
BEGIN
   -- Drive referenced outputs
   y <= y_xhdl0;
   
   
   
   a1 : and_gate
      PORT MAP (
         y_xhdl0(0),
         a(0),
         b(0)
      );
   
   
   a2 : and_gate
      PORT MAP (
         y_xhdl0(1),
         a(1),
         b(1)
      );
   
   
   a3 : and_gate
      PORT MAP (
         y_xhdl0(2),
         a(2),
         b(2)
      );
   
   
   a4 : and_gate
      PORT MAP (
         y_xhdl0(3),
         a(3),
         b(3)
      );
   
   
   a5 : and_gate
      PORT MAP (
         y_xhdl0(4),
         a(4),
         b(4)
      );
   
   
   a6 : and_gate
      PORT MAP (
         y_xhdl0(5),
         a(5),
         b(5)
      );
   
   
   a7 : and_gate
      PORT MAP (
         y_xhdl0(6),
         a(6),
         b(6)
      );
   
   
   a8 : and_gate
      PORT MAP (
         y_xhdl0(7),
         a(7),
         b(7)
      );
   
   
   a9 : and_gate
      PORT MAP (
         y_xhdl0(8),
         a(8),
         b(8)
      );
   
   
   a10 : and_gate
      PORT MAP (
         y_xhdl0(9),
         a(9),
         b(9)
      );
   
   
   a11 : and_gate
      PORT MAP (
         y_xhdl0(10),
         a(10),
         b(10)
      );
   
   
   a12 : and_gate
      PORT MAP (
         y_xhdl0(11),
         a(11),
         b(11)
      );
   
   
   a13 : and_gate
      PORT MAP (
         y_xhdl0(12),
         a(12),
         b(12)
      );
   
   
   a14 : and_gate
      PORT MAP (
         y_xhdl0(13),
         a(13),
         b(13)
      );
   
   
   a15 : and_gate
      PORT MAP (
         y_xhdl0(14),
         a(14),
         b(14)
      );
   
   
   a16 : and_gate
      PORT MAP (
         y_xhdl0(15),
         a(15),
         b(15)
      );
   
END trans;



