----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:06:25
--
--      Input file      : 
--      Component name  : and_gate
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;


ENTITY and_gate IS
   PORT (
      out_xhdl1  : OUT STD_LOGIC;
      a          : IN STD_LOGIC;
      b          : IN STD_LOGIC
   );
END and_gate;

ARCHITECTURE trans OF and_gate IS
   SIGNAL w1        : STD_LOGIC;
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL out_xhdl0 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   out_xhdl1 <= out_xhdl0;
   
   
   
   n1 : NAND_gate
      PORT MAP (
         w1,
         a,
         b
      );
   
   
   n2 : NAND_gate
      PORT MAP (
         out_xhdl0,
         w1,
         w1
      );
   
END trans;



