----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:14:31
--
--      Input file      : 
--      Component name  : computer
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY computer IS
   PORT (
      reset  : IN STD_LOGIC;
      clk    : IN STD_LOGIC
   );
END computer;

ARCHITECTURE trans OF computer IS
   
   SIGNAL pc          : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL address_cpu : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL out_cpu     : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL istr_rom    : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL in_ram      : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL write_cpu   : STD_LOGIC;
   SIGNAL addr        : STD_LOGIC_VECTOR(5 DOWNTO 0);
BEGIN
   
   
   
   c1 : cpu
      PORT MAP (
         out_cpu,
         address_cpu,
         pc,
         write_cpu,
         istr_rom,
         reset,
         clk,
         in_ram
      );
   
   
   c2 : ram64
      PORT MAP (
         in_ram,
         out_cpu,
         write_cpu,
         address_cpu(15 DOWNTO 10),
         clk
      );
   
   
   c3 : rom_add
      PORT MAP (
         istr_rom,
         pc(4 DOWNTO 0),
         clk
      );
   
END trans;





