----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:22:24
--
--      Input file      : 
--      Component name  : demux_16_14
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY demux_16_14 IS
   PORT (
      a         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      b         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      c         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      d         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      s         : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      in_xhdl4  : IN STD_LOGIC_VECTOR(15 DOWNTO 0)
   );
END demux_16_14;

ARCHITECTURE trans OF demux_16_14 IS
   SIGNAL w1      : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL w2      : STD_LOGIC_VECTOR(15 DOWNTO 0);
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL a_xhdl0 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL b_xhdl1 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL c_xhdl2 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL d_xhdl3 : STD_LOGIC_VECTOR(15 DOWNTO 0);
BEGIN
   -- Drive referenced outputs
   a <= a_xhdl0;
   b <= b_xhdl1;
   c <= c_xhdl2;
   d <= d_xhdl3;
   
   
   
   d1 : demux_16_21
      PORT MAP (
         w1,
         w2,
         in_xhdl4,
         s(1)
      );
   
   
   d2 : demux_16_21
      PORT MAP (
         a_xhdl0,
         b_xhdl1,
         w1,
         s(0)
      );
   
   
   d3 : demux_16_21
      PORT MAP (
         c_xhdl2,
         d_xhdl3,
         w2,
         s(0)
      );
   
END trans;






