----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:49:23
--
--      Input file      : 
--      Component name  : demux16_18
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY demux16_18 IS
   PORT (
      a         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      b         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      c         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      d         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      e         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      f         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      g         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      h         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      s         : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      in_xhdl8  : IN STD_LOGIC_VECTOR(15 DOWNTO 0)
   );
END demux16_18;

ARCHITECTURE trans OF demux16_18 IS
   COMPONENT demux_16_14 IS
      PORT (
         a         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
         b         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
         c         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
         d         : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
         s         : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
         in_xhdl4  : IN STD_LOGIC_VECTOR(15 DOWNTO 0)
      );
   END COMPONENT;
   
   SIGNAL w1      : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL w2      : STD_LOGIC_VECTOR(15 DOWNTO 0);
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL a_xhdl0 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL b_xhdl1 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL c_xhdl2 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL d_xhdl3 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL e_xhdl4 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL f_xhdl5 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL g_xhdl6 : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL h_xhdl7 : STD_LOGIC_VECTOR(15 DOWNTO 0);
BEGIN
   -- Drive referenced outputs
   a <= a_xhdl0;
   b <= b_xhdl1;
   c <= c_xhdl2;
   d <= d_xhdl3;
   e <= e_xhdl4;
   f <= f_xhdl5;
   g <= g_xhdl6;
   h <= h_xhdl7;
   
   
   
   d1 : demux_16_21
      PORT MAP (
         w1,
         w2,
         in_xhdl8,
         s(2)
      );
   
   
   d2 : demux_16_14
      PORT MAP (
         a_xhdl0,
         b_xhdl1,
         c_xhdl2,
         d_xhdl3,
         s(1 DOWNTO 0),
         w1
      );
   
   
   d3 : demux_16_14
      PORT MAP (
         e_xhdl4,
         f_xhdl5,
         g_xhdl6,
         h_xhdl7,
         s(1 DOWNTO 0),
         w2
      );
   
END trans;



