----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:25:13
--
--      Input file      : 
--      Component name  : demux_12
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY demux_12 IS
   PORT (
      a         : OUT STD_LOGIC;
      b         : OUT STD_LOGIC;
      in_xhdl2  : IN STD_LOGIC;
      sel       : IN STD_LOGIC
   );
END demux_12;

ARCHITECTURE trans OF demux_12 IS
   SIGNAL w1      : STD_LOGIC;
   SIGNAL w2      : STD_LOGIC;
   SIGNAL w3      : STD_LOGIC;
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL a_xhdl0 : STD_LOGIC;
   SIGNAL b_xhdl1 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   a <= a_xhdl0;
   b <= b_xhdl1;
   
   
   
   d1 : NAND_gate
      PORT MAP (
         w1,
         sel,
         sel
      );
   
   
   d2 : NAND_gate
      PORT MAP (
         w2,
         in_xhdl2,
         w1
      );
   
   
   d3 : NAND_gate
      PORT MAP (
         w3,
         in_xhdl2,
         sel
      );
   
   
   d4 : NAND_gate
      PORT MAP (
         a_xhdl0,
         w2,
         w2
      );
   
   
   d5 : NAND_gate
      PORT MAP (
         b_xhdl1,
         w3,
         w3
      );
   
END trans;


