----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:19:47
--
--      Input file      : 
--      Component name  : demux_14
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;


ENTITY demux_14 IS
   PORT (
      a         : OUT STD_LOGIC;
      b         : OUT STD_LOGIC;
      c         : OUT STD_LOGIC;
      d         : OUT STD_LOGIC;
      s         : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      in_xhdl4  : IN STD_LOGIC
   );
END demux_14;

ARCHITECTURE trans OF demux_14 IS
   SIGNAL w1      : STD_LOGIC;
   SIGNAL w2      : STD_LOGIC;
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL a_xhdl0 : STD_LOGIC;
   SIGNAL b_xhdl1 : STD_LOGIC;
   SIGNAL c_xhdl2 : STD_LOGIC;
   SIGNAL d_xhdl3 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   a <= a_xhdl0;
   b <= b_xhdl1;
   c <= c_xhdl2;
   d <= d_xhdl3;
   
   
   
   d1 : demux_12
      PORT MAP (
         w1,
         w2,
         in_xhdl4,
         s(1)
      );
   
   
   d2 : demux_12
      PORT MAP (
         a_xhdl0,
         b_xhdl1,
         w1,
         s(0)
      );
   
   
   d3 : demux_12
      PORT MAP (
         c_xhdl2,
         d_xhdl3,
         w2,
         s(0)
      );
   
END trans;


