----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:30:16
--
--      Input file      : 
--      Component name  : dff
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY dff IS
   PORT (
      q    : OUT STD_LOGIC;
      d    : IN STD_LOGIC;
      clk  : IN STD_LOGIC
   );
END dff;

ARCHITECTURE trans OF dff IS
   SIGNAL qbar    : STD_LOGIC;
   SIGNAL w1      : STD_LOGIC;
   SIGNAL w2      : STD_LOGIC;
   SIGNAL w3      : STD_LOGIC;
   SIGNAL w4      : STD_LOGIC;
   SIGNAL w5      : STD_LOGIC;
   SIGNAL w6      : STD_LOGIC;
   SIGNAL w7      : STD_LOGIC;
   SIGNAL w8      : STD_LOGIC;
   SIGNAL w9      : STD_LOGIC;
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL q_xhdl0 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   q <= q_xhdl0;
   
   
   
   n1 : NAND_gate
      PORT MAP (
         w1,
         d,
         clk
      );
   
   
   n3 : NOT_gate
      PORT MAP (
         w2,
         d
      );
   
   
   n2 : NAND_gate
      PORT MAP (
         w3,
         w2,
         clk
      );
   
   
   n4 : NAND_gate
      PORT MAP (
         w4,
         w1,
         w5
      );
   
   
   n5 : NAND_gate
      PORT MAP (
         w5,
         w3,
         w4
      );
   
   
   n6 : NOT_gate
      PORT MAP (
         w6,
         clk
      );
   
   
   n7 : NAND_gate
      PORT MAP (
         w7,
         w4,
         w6
      );
   
   
   n8 : NOT_gate
      PORT MAP (
         w8,
         w4
      );
   
   
   n9 : NAND_gate
      PORT MAP (
         w9,
         w8,
         w6
      );
   
   
   n10 : NAND_gate
      PORT MAP (
         q_xhdl0,
         w7,
         qbar
      );
   
   
   n11 : NAND_gate
      PORT MAP (
         qbar,
         q_xhdl0,
         w9
      );
   
END trans;



