----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:35:16
--
--      Input file      : 
--      Component name  : fa_16
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY fa_16 IS
   PORT (
      sum   : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      cout  : OUT STD_LOGIC;
      a     : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
      b     : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
      cin   : IN STD_LOGIC
   );
END fa_16;

ARCHITECTURE trans OF fa_16 IS
   COMPONENT fulladder IS
      PORT (
         sum   : OUT STD_LOGIC;
         carry : OUT STD_LOGIC;
         a     : IN STD_LOGIC;
         b     : IN STD_LOGIC;
         c     : IN STD_LOGIC
      );
   END COMPONENT;
   
   
   SIGNAL w1         : STD_LOGIC;
   SIGNAL w2         : STD_LOGIC;
   SIGNAL w3         : STD_LOGIC;
   SIGNAL w4         : STD_LOGIC;
   SIGNAL w5         : STD_LOGIC;
   SIGNAL w6         : STD_LOGIC;
   SIGNAL w7         : STD_LOGIC;
   SIGNAL w8         : STD_LOGIC;
   SIGNAL w9         : STD_LOGIC;
   SIGNAL w10        : STD_LOGIC;
   SIGNAL w11        : STD_LOGIC;
   SIGNAL w12        : STD_LOGIC;
   SIGNAL w13        : STD_LOGIC;
   SIGNAL w14        : STD_LOGIC;
   SIGNAL w15        : STD_LOGIC;
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL sum_xhdl1  : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL cout_xhdl0 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   sum <= sum_xhdl1;
   cout <= cout_xhdl0;
   
   
   f1 : fulladder
      PORT MAP (
         sum_xhdl1(0),
         w1,
         a(0),
         b(0),
         cin
      );
   
   
   f2 : fulladder
      PORT MAP (
         sum_xhdl1(1),
         w2,
         a(1),
         b(1),
         w1
      );
   
   
   f3 : fulladder
      PORT MAP (
         sum_xhdl1(2),
         w3,
         a(2),
         b(2),
         w2
      );
   
   
   f4 : fulladder
      PORT MAP (
         sum_xhdl1(3),
         w4,
         a(3),
         b(3),
         w3
      );
   
   
   f5 : fulladder
      PORT MAP (
         sum_xhdl1(4),
         w5,
         a(4),
         b(4),
         w4
      );
   
   
   f6 : fulladder
      PORT MAP (
         sum_xhdl1(5),
         w6,
         a(5),
         b(5),
         w5
      );
   
   
   f7 : fulladder
      PORT MAP (
         sum_xhdl1(6),
         w7,
         a(6),
         b(6),
         w6
      );
   
   
   f8 : fulladder
      PORT MAP (
         sum_xhdl1(7),
         w8,
         a(7),
         b(7),
         w7
      );
   
   
   f9 : fulladder
      PORT MAP (
         sum_xhdl1(8),
         w9,
         a(8),
         b(8),
         w8
      );
   
   
   f10 : fulladder
      PORT MAP (
         sum_xhdl1(9),
         w10,
         a(9),
         b(9),
         w9
      );
   
   
   f11 : fulladder
      PORT MAP (
         sum_xhdl1(10),
         w11,
         a(10),
         b(10),
         w10
      );
   
   
   f12 : fulladder
      PORT MAP (
         sum_xhdl1(11),
         w12,
         a(11),
         b(11),
         w11
      );
   
   
   f13 : fulladder
      PORT MAP (
         sum_xhdl1(12),
         w13,
         a(12),
         b(12),
         w12
      );
   
   
   f14 : fulladder
      PORT MAP (
         sum_xhdl1(13),
         w14,
         a(13),
         b(13),
         w13
      );
   
   
   f15 : fulladder
      PORT MAP (
         sum_xhdl1(14),
         w15,
         a(14),
         b(14),
         w14
      );
   
   
   f16 : fulladder
      PORT MAP (
         sum_xhdl1(15),
         cout_xhdl0,
         a(15),
         b(15),
         w15
      );
   
END trans;






