----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:33:49
--
--      Input file      : 
--      Component name  : fulladder
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY fulladder IS
   PORT (
      sum    : OUT STD_LOGIC;
      carry  : OUT STD_LOGIC;
      a      : IN STD_LOGIC;
      b      : IN STD_LOGIC;
      c      : IN STD_LOGIC
   );
END fulladder;

ARCHITECTURE trans OF fulladder IS
   SIGNAL w1          : STD_LOGIC;
   SIGNAL w2          : STD_LOGIC;
   SIGNAL w3          : STD_LOGIC;
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL sum_xhdl1   : STD_LOGIC;
   SIGNAL carry_xhdl0 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   sum <= sum_xhdl1;
   carry <= carry_xhdl0;
   
   
   
   f1 : halfadder
      PORT MAP (
         w1,
         w3,
         a,
         b
      );
   
   
   f2 : halfadder
      PORT MAP (
         sum_xhdl1,
         w2,
         w1,
         c
      );
   
   
   f3 : or_gate
      PORT MAP (
         carry_xhdl0,
         w3,
         w2
      );
   
END trans;


