----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Fri Feb 19 2016 15:36:55
--
--      Input file      : 
--      Component name  : halfadder
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY halfadder IS
   PORT (
      sum    : OUT STD_LOGIC;
      carry  : OUT STD_LOGIC;
      a      : IN STD_LOGIC;
      b      : IN STD_LOGIC
   );
END halfadder;

ARCHITECTURE trans OF halfadder IS
   SIGNAL w1          : STD_LOGIC;
   SIGNAL w2          : STD_LOGIC;
   SIGNAL w3          : STD_LOGIC;
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL sum_xhdl1   : STD_LOGIC;
   SIGNAL carry_xhdl0 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   sum <= sum_xhdl1;
   carry <= carry_xhdl0;
   
   
   
   h1 : NAND_gate
      PORT MAP (
         w1,
         a,
         b
      );
   
   
   h2 : NAND_gate
      PORT MAP (
         w2,
         a,
         w1
      );
   
   
   h3 : NAND_gate
      PORT MAP (
         w3,
         w1,
         b
      );
   
   
   h4 : NAND_gate
      PORT MAP (
         sum_xhdl1,
         w2,
         w3
      );
   
   
   h5 : NAND_gate
      PORT MAP (
         carry_xhdl0,
         w1,
         w1
      );
   
END trans;


