----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Thu Mar 3 2016 09:33:02
--
--      Input file      : 
--      Component name  : notgate_16
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY notgate_16 IS
   PORT (
      y  : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      a  : IN STD_LOGIC_VECTOR(15 DOWNTO 0)
   );
END notgate_16;

ARCHITECTURE trans OF notgate_16 IS
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL y_xhdl0 : STD_LOGIC_VECTOR(15 DOWNTO 0);
BEGIN
   -- Drive referenced outputs
   y <= y_xhdl0;
   
   
   
   n1 : NOT_gate
      PORT MAP (
         y_xhdl0(0),
         a(0)
      );
   
   
   n2 : NOT_gate
      PORT MAP (
         y_xhdl0(1),
         a(1)
      );
   
   
   n3 : NOT_gate
      PORT MAP (
         y_xhdl0(2),
         a(2)
      );
   
   
   n4 : NOT_gate
      PORT MAP (
         y_xhdl0(3),
         a(3)
      );
   
   
   n5 : NOT_gate
      PORT MAP (
         y_xhdl0(4),
         a(4)
      );
   
   
   n6 : NOT_gate
      PORT MAP (
         y_xhdl0(5),
         a(5)
      );
   
   
   n7 : NOT_gate
      PORT MAP (
         y_xhdl0(6),
         a(6)
      );
   
   
   n8 : NOT_gate
      PORT MAP (
         y_xhdl0(7),
         a(7)
      );
   
   
   n9 : NOT_gate
      PORT MAP (
         y_xhdl0(8),
         a(8)
      );
   
   
   n10 : NOT_gate
      PORT MAP (
         y_xhdl0(9),
         a(9)
      );
   
   
   n11 : NOT_gate
      PORT MAP (
         y_xhdl0(10),
         a(10)
      );
   
   
   n12 : NOT_gate
      PORT MAP (
         y_xhdl0(11),
         a(11)
      );
   
   
   n13 : NOT_gate
      PORT MAP (
         y_xhdl0(12),
         a(12)
      );
   
   
   n14 : NOT_gate
      PORT MAP (
         y_xhdl0(13),
         a(13)
      );
   
   
   n15 : NOT_gate
      PORT MAP (
         y_xhdl0(14),
         a(14)
      );
   
   
   n16 : NOT_gate
      PORT MAP (
         y_xhdl0(15),
         a(15)
      );
   
END trans;


