----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Thu Mar 3 2016 09:40:51
--
--      Input file      : 
--      Component name  : or8_gate
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY or8_gate IS
   PORT (
      out_xhdl2  : OUT STD_LOGIC;
      in_xhdl0   : IN STD_LOGIC_VECTOR(7 DOWNTO 0)
   );
END or8_gate;

ARCHITECTURE trans OF or8_gate IS
   COMPONENT or_gate IS
      PORT (
         out_xhdl1  : OUT STD_LOGIC;
         a          : IN STD_LOGIC;
         b          : IN STD_LOGIC
      );
   END COMPONENT;
   
   SIGNAL w1        : STD_LOGIC;
   SIGNAL w2        : STD_LOGIC;
   SIGNAL w3        : STD_LOGIC;
   SIGNAL w4        : STD_LOGIC;
   SIGNAL w5        : STD_LOGIC;
   SIGNAL w6        : STD_LOGIC;
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL out_xhdl1 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   out_xhdl2 <= out_xhdl1;
   
   
   
   o1 : or_gate
      PORT MAP (
         w1,
         in_xhdl0(0),
         in_xhdl0(1)
      );
   
   
   o2 : or_gate
      PORT MAP (
         w2,
         w1,
         in_xhdl0(2)
      );
   
   
   o3 : or_gate
      PORT MAP (
         w3,
         w2,
         in_xhdl0(3)
      );
   
   
   o4 : or_gate
      PORT MAP (
         w4,
         w3,
         in_xhdl0(4)
      );
   
   
   o5 : or_gate
      PORT MAP (
         w5,
         w4,
         in_xhdl0(5)
      );
   
   
   o6 : or_gate
      PORT MAP (
         w6,
         w5,
         in_xhdl0(6)
      );
   
   
   o7 : or_gate
      PORT MAP (
         out_xhdl1,
         w6,
         in_xhdl0(7)
      );
   
END trans;



