----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Thu Mar 3 2016 09:36:33
--
--      Input file      : 
--      Component name  : or_gate
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY or_gate IS
   PORT (
      out_xhdl1  : OUT STD_LOGIC;
      a          : IN STD_LOGIC;
      b          : IN STD_LOGIC
   );
END or_gate;

ARCHITECTURE trans OF or_gate IS
   SIGNAL w1        : STD_LOGIC;
   SIGNAL w2        : STD_LOGIC;
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL out_xhdl0 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   out_xhdl1 <= out_xhdl0;
   
   
   
   o1 : NAND_gate
      PORT MAP (
         w1,
         a,
         a
      );
   
   
   o2 : NAND_gate
      PORT MAP (
         w2,
         b,
         b
      );
   
   
   o3 : NAND_gate
      PORT MAP (
         out_xhdl0,
         w1,
         w2
      );
   
END trans;


