----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 4.2.5 May 28, 2012
-- Thu Mar 3 2016 09:45:09
--
--      Input file      : 
--      Component name  : pc
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;

ENTITY pc IS
   PORT (
      out_xhdl2  : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      in_xhdl0   : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
      inc        : IN STD_LOGIC;
      load       : IN STD_LOGIC;
      reset      : IN STD_LOGIC;
      clk        : IN STD_LOGIC
   );
END pc;

ARCHITECTURE trans OF pc IS
   COMPONENT and_gate IS
      PORT (
         out_xhdl1  : OUT STD_LOGIC;
         a          : IN STD_LOGIC;
         b          : IN STD_LOGIC
      );
   END COMPONENT;
   
   COMPONENT fa_16 IS
      PORT (
         sum        : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
         cout       : OUT STD_LOGIC;
         a          : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
         b          : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
         cin        : IN STD_LOGIC
      );
   END COMPONENT;
   
   SIGNAL w4        : STD_LOGIC;
   SIGNAL w6        : STD_LOGIC;
   SIGNAL cz        : STD_LOGIC;
   SIGNAL w1        : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL w2        : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL w3        : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL w5        : STD_LOGIC_VECTOR(15 DOWNTO 0);
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL out_xhdl1 : STD_LOGIC_VECTOR(15 DOWNTO 0);
BEGIN
   -- Drive referenced outputs
   out_xhdl2 <= out_xhdl1;
   
   
   
   m1 : mux16_21
      PORT MAP (
         w2,
         load,
         w1,
         in_xhdl0
      );
   
   
   m2 : mux16_21
      PORT MAP (
         w3,
         w4,
         w2,
         w5
      );
   
   
   m3 : mux16_21
      PORT MAP (
         out_xhdl1,
         reset,
         w3,
         "0000000000000000"
      );
   
   
   n1 : NOT_gate
      PORT MAP (
         w6,
         load
      );
   
   
   a1 : and_gate
      PORT MAP (
         w4,
         inc,
         w6
      );
   
   
   f1 : fa_16
      PORT MAP (
         w5,
         cz,
         w2,
         '1',
         '0'
      );
   
   
   r1 : register_16
      PORT MAP (
         w1,
         out_xhdl1,
         '1',
         clk
      );
   
END trans;



